import{i as n,S as L,a as w}from"./assets/vendor-MjawMu3A.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const S=document.querySelector("#search-form"),m=document.querySelector(".gallery"),u=document.querySelector(".loader"),i=document.querySelector(".load-more-btn"),k="53317222-33ad4c1be86b2938ae2a211ff";let f=40,l=1,d="",p=0;async function y(o,r){const s="https://pixabay.com/api/",a=new URLSearchParams({key:`${k}`,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:f});try{const t=(await w.get(s,{params:a})).data;if(t.hits.length===0)throw new Error("No images found");return t}catch(e){throw e}}S.addEventListener("submit",v);function v(o){if(o.preventDefault(),l=1,d=o.currentTarget.elements.searchQuery.value.trim(),d===""){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}m.innerHTML="",u.style.display="block",y(d,l).then(r=>{const s=r.hits.map(g).join("");p=r.totalHits,i.style.display="block",m.insertAdjacentHTML("beforeend",s),h.refresh(),f*l>=p&&(i.style.display="none",n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}).catch(r=>{r.message=="No images found"?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"}):n.error({title:"Error",message:`An API error occurred: ${r.message}`,position:"topRight"})}).finally(()=>{u.style.display="none"}),o.currentTarget.reset()}function P(){l+=1,u.style.display="block",i.style.display="none",y(d,l).then(o=>{const r=o.hits.map(g).join("");m.insertAdjacentHTML("beforeend",r),h.refresh();const s=document.querySelector(".gallery-item");if(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}f*l<p?i.style.display="block":(i.style.display="none",n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}).catch(o=>{n.error({title:"Error",message:"Failed to load more images. Please check your network connection.",position:"topRight"})}).finally(()=>{u.style.display="none"})}function g(o){const{webformatURL:r,largeImageURL:s,tags:a,likes:e,views:t,comments:c,downloads:b}=o;return`
    <li class="gallery-item">
        <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${r}" alt="${a}" />
            <div class="info-box">
                <p class="info-item"><b>Likes</b>${e}</p>
                <p class="info-item"><b>Views</b>${t}</p>
                <p class="info-item"><b>Comments</b>${c}</p>
                <p class="info-item"><b>Downloads</b>${b}</p>
            </div>
        </a>
    </li>
    `}const h=new L(".gallery a",{captionsData:"alt",captionDelay:250});i.addEventListener("click",P);
//# sourceMappingURL=index.js.map
